//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class CFCA_Settlement_Info
    {
        public string CFCAId { get; set; }
        public string TxType { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string USRNBR { get; set; }
        public string USRNAM { get; set; }
        public string ACCSEQ { get; set; }
        public string EACNAM { get; set; }
        public string EACNBR { get; set; }
        public string EACBNK { get; set; }
        public string PVCCOD { get; set; }
        public string CTYCOD { get; set; }
        public string BNKNAM { get; set; }
        public string BRDNBR { get; set; }
        public string CTFTYP { get; set; }
        public string CTFIDC { get; set; }
        public string ROLTYP { get; set; }
        public string SIGTIM { get; set; }
    }
    
}
