//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class CFCA_Pay_Info
    {
        public string CFCAId { get; set; }
        public string InstitutionID { get; set; }
        public string OrderNo { get; set; }
        public string TxType { get; set; }
        public string PaymentNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    }
    
}
