//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class CMBC_BankAccount
    {
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountNO { get; set; }
        public string AccountBank { get; set; }
        public string BranchBankCode { get; set; }
        public string BranchBankName { get; set; }
        public string BankCode { get; set; }
        public string BankProvince { get; set; }
        public string BankCity { get; set; }
        public string BankProvinceCode { get; set; }
        public string BankCityCode { get; set; }
        public string Brdnbr { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string IDcard { get; set; }
        public string Ctftyp { get; set; }
        public string Sigtim { get; set; }
        public string Sigdat { get; set; }
        public string Sigtyp { get; set; }
        public string CmbcAccountId { get; set; }
        public string Usrnbr { get; set; }
    }
    
}
