//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_AlliedBankCode
    {
        public int BankID { get; set; }
        public string BankType { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string BankCodeFirstNum { get; set; }
        public string AreaCode { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
    }
    
}
