//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_CreditScore
    {
        public string OrderNo { get; set; }
        public string UserId { get; set; }
        public string Usrnbr { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int SendStatus { get; set; }
        public string SendMsg { get; set; }
        public int OrderType { get; set; }
        public string ProjectCode { get; set; }
        public string RunningNo { get; set; }
        public Nullable<System.DateTime> RepayBegin { get; set; }
        public System.DateTime ValueBegin { get; set; }
        public int Duration { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string AmountType { get; set; }
        public string InstitutionNo { get; set; }
    }
    
}
