//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_DepositApply
    {
        public string DepositApplyID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public decimal DepositAmount { get; set; }
        public int DepositDeadline { get; set; }
        public string BankInfo { get; set; }
        public string DistrictID { get; set; }
        public string DepositProductID { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public int FeedbackState { get; set; }
    
        public virtual F_DepositProduct F_DepositProduct { get; set; }
        public virtual F_District F_District { get; set; }
    }
    
}
