//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_District
    {
        public F_District()
        {
            this.F_DepositApply = new HashSet<F_DepositApply>();
        }
    
        public string DistrictID { get; set; }
        public string DistrictName { get; set; }
        public string ParentID { get; set; }
    
        public virtual ICollection<F_DepositApply> F_DepositApply { get; set; }
    }
    
}
