//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Feedback
    {
        public string FeedbackId { get; set; }
        public string Contents { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ApplyID { get; set; }
        public int Category { get; set; }
        public int Status { get; set; }
    }
    
}
