//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_GenerateCmdRecord
    {
        public string GenerateId { get; set; }
        public string FinancingId { get; set; }
        public System.DateTime GenerateTime { get; set; }
        public string OperUserId { get; set; }
    
        public virtual F_Financing F_Financing { get; set; }
    }
    
}
