//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_InvestmentOrderApply
    {
        public string InvestmentOrderApplyId { get; set; }
        public decimal CanInvestment { get; set; }
        public decimal ExpectYearInterest { get; set; }
        public string Duration { get; set; }
        public string Contact { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserId { get; set; }
    }
    
}
