//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Intention
    {
        public string IntentionId { get; set; }
        public string FinancingId { get; set; }
        public int PartsCount { get; set; }
        public decimal Amount { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public string CreateUserPhonNum { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual F_Financing F_Financing { get; set; }
    }
    
}
