//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Investment_WhiteList
    {
        public string ID { get; set; }
        public string FinancingId { get; set; }
        public string WhiteName { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual F_Financing F_Financing { get; set; }
    }
    
}
