//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_IndexAD
    {
        public int ID { get; set; }
        public string FinancingId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public decimal Amount { get; set; }
        public int Duration { get; set; }
        public decimal InvestmentInterest { get; set; }
        public int ProjectStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
        public decimal Progress { get; set; }
        public int FinanceApplyStatus { get; set; }
        public int ProjectType { get; set; }
    }
    
}
