//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Investment_Order
    {
        public F_Investment_Order()
        {
            this.F_Repay_OrderDetail = new HashSet<F_Repay_OrderDetail>();
        }
    
        public string OrderNo { get; set; }
        public string FinancingId { get; set; }
        public string ProjectName { get; set; }
        public int PartsCount { get; set; }
        public decimal PayAmount { get; set; }
        public int PayStatus { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string PayUserId { get; set; }
        public string PayUserName { get; set; }
        public Nullable<int> PayType { get; set; }
        public string PayChannel { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public string CreateCompanyId { get; set; }
        public string CreateCompanyName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string RunningNO { get; set; }
        public int SendCmdStaus { get; set; }
        public decimal Actualpayments { get; set; }
        public int IsExcess { get; set; }
        public int OrderFrom { get; set; }
    
        public virtual F_Financing F_Financing { get; set; }
        public virtual ICollection<F_Repay_OrderDetail> F_Repay_OrderDetail { get; set; }
    }
    
}
