//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Income
    {
        public int IncomeId { get; set; }
        public string FinancingId { get; set; }
        public string OrderNo { get; set; }
        public int IncomeNumber { get; set; }
        public System.DateTime IncomeTime { get; set; }
        public decimal Amount { get; set; }
        public decimal Capital { get; set; }
        public decimal Interest { get; set; }
    }
    
}
