//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_LetterCredit
    {
        public string LetterCreditId { get; set; }
        public string FinancingId { get; set; }
        public int LCType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public string Code { get; set; }
        public decimal ValuesAmount { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
    
        public virtual F_Financing F_Financing { get; set; }
    }
    
}
