//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_LoanProduct
    {
        public F_LoanProduct()
        {
            this.F_LoanApply = new HashSet<F_LoanApply>();
        }
    
        public string LoanProductID { get; set; }
        public string Name { get; set; }
        public string Introduction { get; set; }
        public string ApplyUses { get; set; }
        public int IsMortgage { get; set; }
        public decimal MinAmount { get; set; }
        public decimal MaxAmount { get; set; }
        public int MinYearLimit { get; set; }
        public int MaxYearLimit { get; set; }
    
        public virtual ICollection<F_LoanApply> F_LoanApply { get; set; }
    }
    
}
