//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_LoanApply
    {
        public string LoanApplyID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal TotalAssets { get; set; }
        public decimal TotalLiabilities { get; set; }
        public decimal SalesRevenue { get; set; }
        public decimal GrossProfit { get; set; }
        public int OperationTime { get; set; }
        public int LoanYear { get; set; }
        public int IsEstate { get; set; }
        public int IsLocal { get; set; }
        public int IsOtherCredit { get; set; }
        public string PersonalAssets { get; set; }
        public string LoanProductID { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public int FeedbackState { get; set; }
        public string City { get; set; }
    
        public virtual F_LoanProduct F_LoanProduct { get; set; }
    }
    
}
