//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_OSLReSend
    {
        public string TaskSn { get; set; }
        public string CmdId { get; set; }
        public string SourceTaskSn { get; set; }
        public string OrderNo { get; set; }
        public string OrderDetailNo { get; set; }
        public string ProjectCode { get; set; }
        public int OrderType { get; set; }
        public decimal OrderAmount { get; set; }
        public int BankType { get; set; }
        public string AccountBank { get; set; }
        public string AccountName { get; set; }
        public string AccountNO { get; set; }
        public string BankCode { get; set; }
        public string BranchBankName { get; set; }
        public string BankProvince { get; set; }
        public string BankCity { get; set; }
        public string BankProvinceCode { get; set; }
        public string BankCityCode { get; set; }
        public string Brdnbr { get; set; }
        public string Ctftyp { get; set; }
        public string Ctfidc { get; set; }
        public string Sigtim { get; set; }
        public string Sigdat { get; set; }
        public string Sigtyp { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public int CStatus { get; set; }
        public string RunningNo { get; set; }
        public string Usrnbr { get; set; }
        public string Accseq { get; set; }
        public bool IsResend { get; set; }
    }
    
}
