//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Repay_OrderDetail
    {
        public string Repay_OrderDetailId { get; set; }
        public string OrderNo { get; set; }
        public string InvestmentOrderNo { get; set; }
        public System.DateTime RepaymentDate { get; set; }
        public decimal RepaymentAmount { get; set; }
        public decimal Capital { get; set; }
        public decimal Interest { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string AccountBank { get; set; }
        public string PayUserId { get; set; }
        public string FinancingId { get; set; }
    
        public virtual F_Investment_Order F_Investment_Order { get; set; }
    }
    
}
