//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Service_Log
    {
        public F_Service_Log()
        {
            this.F_Service_Param = new HashSet<F_Service_Param>();
        }
    
        public string ServiceOperateID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceUrl { get; set; }
        public string ServiceMethod { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<F_Service_Param> F_Service_Param { get; set; }
    }
    
}
