//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_SettlementProduct
    {
        public F_SettlementProduct()
        {
            this.F_SettlementApply = new HashSet<F_SettlementApply>();
        }
    
        public string SettlementProductID { get; set; }
        public string Name { get; set; }
        public string Introduction { get; set; }
    
        public virtual ICollection<F_SettlementApply> F_SettlementApply { get; set; }
    }
    
}
