//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_Service_Param
    {
        public int ID { get; set; }
        public string ServiceOperateID { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
    
        public virtual F_Service_Log F_Service_Log { get; set; }
    }
    
}
