//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class F_UserAgreement
    {
        public string UserAgreementId { get; set; }
        public string UserId { get; set; }
        public int AgreementType { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
    
}
