//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class FM_OrderDealTrack_BAK
    {
        public string ProjectCode { get; set; }
        public string OrderNo { get; set; }
        public string OrderDetailNo { get; set; }
        public int OrderType { get; set; }
        public int OrderDealTrackStatus { get; set; }
        public string RunningNo { get; set; }
        public string DealCode { get; set; }
        public string DealText { get; set; }
        public string TrackResponse { get; set; }
        public System.DateTime CmdTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string ZJ_AccountType { get; set; }
        public string ZJ_Amount { get; set; }
        public string ZJ_AccountName { get; set; }
        public string ZJ_AccountNumber { get; set; }
        public string ZJ_BankID { get; set; }
        public string ZJ_BranchName { get; set; }
        public string ZJ_City { get; set; }
        public string ZJ_Province { get; set; }
        public string ZJ_InstitutionID { get; set; }
        public string ZJ_OrderNo { get; set; }
        public string ZJ_Remark { get; set; }
        public string ZJ_SerialNumber { get; set; }
        public string ZJ_Status { get; set; }
        public string ZJ_PaymentAccountName { get; set; }
        public string ZJ_PaymentAccountNumber { get; set; }
    }
    
}
