//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class FM_ProjectCheckRecord
    {
        public string ProjectCheckRecordId { get; set; }
        public string ProjectId { get; set; }
        public int ProjectCheckType { get; set; }
        public int ProjectCheckStatus { get; set; }
        public string CheckUserId { get; set; }
        public string CheckUserName { get; set; }
        public System.DateTime CheckTime { get; set; }
        public string Remark { get; set; }
    }
    
}
