//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Mvc_Myhtmltest.Models
{
    public partial class FinanceEntity : DbContext
    {
        public FinanceEntity()
            : base("name=FinanceEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CFCA_Pay_Info> CFCA_Pay_Info { get; set; }
        public DbSet<CFCA_Settlement_Info> CFCA_Settlement_Info { get; set; }
        public DbSet<CMBC_BankAccount> CMBC_BankAccount { get; set; }
        public DbSet<CMBC_Map> CMBC_Map { get; set; }
        public DbSet<F_Aduit_Record> F_Aduit_Record { get; set; }
        public DbSet<F_AlliedBankCode> F_AlliedBankCode { get; set; }
        public DbSet<F_BankAccount> F_BankAccount { get; set; }
        public DbSet<F_CreditScore> F_CreditScore { get; set; }
        public DbSet<F_DepositApply> F_DepositApply { get; set; }
        public DbSet<F_DepositProduct> F_DepositProduct { get; set; }
        public DbSet<F_District> F_District { get; set; }
        public DbSet<F_Feedback> F_Feedback { get; set; }
        public DbSet<F_Financing> F_Financing { get; set; }
        public DbSet<F_Financing_SMS> F_Financing_SMS { get; set; }
        public DbSet<F_GenerateCmdRecord> F_GenerateCmdRecord { get; set; }
        public DbSet<F_Guarantee> F_Guarantee { get; set; }
        public DbSet<F_Income> F_Income { get; set; }
        public DbSet<F_IndexAD> F_IndexAD { get; set; }
        public DbSet<F_Intention> F_Intention { get; set; }
        public DbSet<F_Investment_Order> F_Investment_Order { get; set; }
        public DbSet<F_Investment_Order_Push> F_Investment_Order_Push { get; set; }
        public DbSet<F_Investment_WhiteList> F_Investment_WhiteList { get; set; }
        public DbSet<F_InvestmentOrder_Agent> F_InvestmentOrder_Agent { get; set; }
        public DbSet<F_InvestmentOrderApply> F_InvestmentOrderApply { get; set; }
        public DbSet<F_LetterCredit> F_LetterCredit { get; set; }
        public DbSet<F_LoanApply> F_LoanApply { get; set; }
        public DbSet<F_LoanProduct> F_LoanProduct { get; set; }
        public DbSet<F_OperateLog> F_OperateLog { get; set; }
        public DbSet<F_Order_CmdRequest> F_Order_CmdRequest { get; set; }
        public DbSet<F_Order_RunningNO> F_Order_RunningNO { get; set; }
        public DbSet<F_Order_ServiceLog> F_Order_ServiceLog { get; set; }
        public DbSet<F_OSLReSend> F_OSLReSend { get; set; }
        public DbSet<F_Project_Content> F_Project_Content { get; set; }
        public DbSet<F_ProjectBackup> F_ProjectBackup { get; set; }
        public DbSet<F_Repay> F_Repay { get; set; }
        public DbSet<F_Repay_Order> F_Repay_Order { get; set; }
        public DbSet<F_Repay_OrderDetail> F_Repay_OrderDetail { get; set; }
        public DbSet<F_Service_Log> F_Service_Log { get; set; }
        public DbSet<F_Service_Param> F_Service_Param { get; set; }
        public DbSet<F_SettlementApply> F_SettlementApply { get; set; }
        public DbSet<F_SettlementProduct> F_SettlementProduct { get; set; }
        public DbSet<F_SettlementSucRecord> F_SettlementSucRecord { get; set; }
        public DbSet<F_User> F_User { get; set; }
        public DbSet<F_User_IsOpen> F_User_IsOpen { get; set; }
        public DbSet<F_UserActivity> F_UserActivity { get; set; }
        public DbSet<F_UserAgreement> F_UserAgreement { get; set; }
        public DbSet<F_UserRight> F_UserRight { get; set; }
        public DbSet<FM_OrderDealTrack> FM_OrderDealTrack { get; set; }
        public DbSet<FM_OrderDealTrack_BAK> FM_OrderDealTrack_BAK { get; set; }
        public DbSet<FM_ProjectCheckRecord> FM_ProjectCheckRecord { get; set; }
        public DbSet<FM_ProjectCheckRecord1集> FM_ProjectCheckRecord1集 { get; set; }
        public DbSet<MSpeer_conflictdetectionconfigrequest> MSpeer_conflictdetectionconfigrequest { get; set; }
        public DbSet<MSpeer_conflictdetectionconfigresponse> MSpeer_conflictdetectionconfigresponse { get; set; }
        public DbSet<MSpeer_lsns> MSpeer_lsns { get; set; }
        public DbSet<MSpeer_originatorid_history> MSpeer_originatorid_history { get; set; }
        public DbSet<MSpeer_request> MSpeer_request { get; set; }
        public DbSet<MSpeer_response> MSpeer_response { get; set; }
        public DbSet<MSpeer_topologyrequest> MSpeer_topologyrequest { get; set; }
        public DbSet<MSpeer_topologyresponse> MSpeer_topologyresponse { get; set; }
        public DbSet<MSpub_identity_range> MSpub_identity_range { get; set; }
        public DbSet<QCity> QCity { get; set; }
        public DbSet<QProvince> QProvince { get; set; }
        public DbSet<sysarticlecolumns> sysarticlecolumns { get; set; }
        public DbSet<sysarticles> sysarticles { get; set; }
        public DbSet<sysarticleupdates> sysarticleupdates { get; set; }
        public DbSet<syspublications> syspublications { get; set; }
        public DbSet<sysreplservers> sysreplservers { get; set; }
        public DbSet<sysschemaarticles> sysschemaarticles { get; set; }
        public DbSet<syssubscriptions> syssubscriptions { get; set; }
        public DbSet<systranschemas> systranschemas { get; set; }
        public DbSet<UM_ErrorLog> UM_ErrorLog { get; set; }
    }
}
