//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mvc_Myhtmltest.Models
{
    public partial class sysarticlecolumns
    {
        public int artid { get; set; }
        public int colid { get; set; }
        public Nullable<bool> is_udt { get; set; }
        public Nullable<bool> is_xml { get; set; }
        public Nullable<bool> is_max { get; set; }
    }
    
}
