//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class ErrorLog
    {
        public string ID { get; set; }
        public string LogMessage { get; set; }
        public string LogException { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Source { get; set; }
        public string LogLevel { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LogModule { get; set; }
        public string ServerIp { get; set; }
    }
    
}
