//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class FinanceDic
    {
        public string FCode { get; set; }
        public int FPrjType { get; set; }
        public int FPayType { get; set; }
        public string FDesc { get; set; }
        public string InstitutionID { get; set; }
        public string ConnectString { get; set; }
        public string AddressUrl { get; set; }
        public Nullable<byte> NotifyFlag { get; set; }
    }
    
}
