//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class ODS_Order_RunningNO
    {
        public string RunningNo { get; set; }
        public string OrderNo { get; set; }
        public decimal OrderAmount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
    }
    
}
