//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class ODS_User
    {
        public string UserId { get; set; }
        public string Usrnbr { get; set; }
        public string Mobile { get; set; }
        public string UserName { get; set; }
        public string FCode { get; set; }
    }
    
}
