//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace My.DataAccess.PlatformModel
{
    public partial class PlatformEntities1 : DbContext
    {
        public PlatformEntities1()
            : base("name=PlatformEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ErrorLog> ErrorLog { get; set; }
        public DbSet<FinanceDic> FinanceDic { get; set; }
        public DbSet<ODS_BankAccount> ODS_BankAccount { get; set; }
        public DbSet<ODS_Financing> ODS_Financing { get; set; }
        public DbSet<ODS_Guarantee> ODS_Guarantee { get; set; }
        public DbSet<ODS_Investment_Order> ODS_Investment_Order { get; set; }
        public DbSet<ODS_Order_RunningNO> ODS_Order_RunningNO { get; set; }
        public DbSet<ODS_Project_Content> ODS_Project_Content { get; set; }
        public DbSet<ODS_User> ODS_User { get; set; }
        public DbSet<PayStatusNotifyTask> PayStatusNotifyTask { get; set; }
        public DbSet<QtUser_SourceUser> QtUser_SourceUser { get; set; }
        public DbSet<SaleInstitution> SaleInstitution { get; set; }
        public DbSet<SaleInstitutionBlackList> SaleInstitutionBlackList { get; set; }
        public DbSet<SaleInstitutionOrderRecord> SaleInstitutionOrderRecord { get; set; }
        public DbSet<SaleInstitutionPayLog> SaleInstitutionPayLog { get; set; }
        public DbSet<SaleInstitutionPermit> SaleInstitutionPermit { get; set; }
        public DbSet<V_ODS_Financing> V_ODS_Financing { get; set; }
        public DbSet<V_ODS_FinancingDetail> V_ODS_FinancingDetail { get; set; }
        public DbSet<V_ODS_UserOrderInfo> V_ODS_UserOrderInfo { get; set; }
    }
}
