//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class QtUser_SourceUser
    {
        public string QtUserId { get; set; }
        public string SourceID { get; set; }
        public string SourceUsrnbr { get; set; }
        public string SourceUsrnam { get; set; }
        public string SourceUsrMobile { get; set; }
        public string SourceUsrMail { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
    
}
