//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class SaleInstitutionOrderRecord
    {
        public string OrderNo { get; set; }
        public string FinancingId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public int PartsCount { get; set; }
        public decimal PayAmount { get; set; }
        public int PayStatus { get; set; }
        public string PayUserId { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string RunningNo { get; set; }
        public int IsExcess { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string AccountBank { get; set; }
        public string BankCode { get; set; }
        public string BankProvince { get; set; }
        public string BankProvinceCode { get; set; }
        public string BankCity { get; set; }
        public string BankCityCode { get; set; }
        public string BranchBankName { get; set; }
        public string Brdnbr { get; set; }
        public string Ctfidc { get; set; }
        public string Ctftyp { get; set; }
        public string Usage { get; set; }
        public string Remark { get; set; }
        public string SourceID { get; set; }
    }
    
}
