//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class SaleInstitutionPayLog
    {
        public string PayLogId { get; set; }
        public string SourceID { get; set; }
        public int BizCode { get; set; }
        public string OrderNo { get; set; }
        public string PaymentNo { get; set; }
        public string NotificationURL { get; set; }
        public string BankID { get; set; }
        public string Usrnbr { get; set; }
        public string Usrnam { get; set; }
        public string AccountType { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
    
}
