//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class SaleInstitutionBlackList
    {
        public System.Guid ListID { get; set; }
        public string SourceID { get; set; }
        public string FinancingId { get; set; }
        public string FCode { get; set; }
        public string FPrjType { get; set; }
        public Nullable<int> RuleFlag { get; set; }
        public Nullable<byte> DelFlag { get; set; }
    }
    
}
