//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class V_ODS_FinancingDetail
    {
        public string FinancingId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public decimal Amount { get; set; }
        public int PartsCount { get; set; }
        public int MinInvestPartsCount { get; set; }
        public decimal InvestmentInterest { get; set; }
        public int Duration { get; set; }
        public System.DateTime ValueBegin { get; set; }
        public System.DateTime RepayBegin { get; set; }
        public System.DateTime ProjectBeginTime { get; set; }
        public System.DateTime ReadyBeginTime { get; set; }
        public System.DateTime JMBeginTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Useage { get; set; }
        public int RemainPartsCount { get; set; }
        public decimal Progress { get; set; }
        public int ProjectStatus { get; set; }
        public string FCode { get; set; }
        public int FPrjType { get; set; }
        public int FPayType { get; set; }
    }
    
}
