//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.PlatformModel
{
    public partial class V_ODS_UserOrderInfo
    {
        public string FinancingId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public decimal Amount { get; set; }
        public int Duration { get; set; }
        public decimal InvestmentInterest { get; set; }
        public decimal Progress { get; set; }
        public System.DateTime ValueBegin { get; set; }
        public System.DateTime RepayBegin { get; set; }
        public Nullable<int> ProjectExpireDay { get; set; }
        public Nullable<System.DateTime> ActualToFinancingTime { get; set; }
        public Nullable<System.DateTime> ActualToInvestmentTime { get; set; }
        public string AccountBank { get; set; }
        public string AccountName { get; set; }
        public string AccountNO { get; set; }
        public string IDcard { get; set; }
        public string BankProvince { get; set; }
        public string BankCity { get; set; }
        public string BranchBankName { get; set; }
        public string OrderNo { get; set; }
        public int PartsCount { get; set; }
        public decimal PayAmount { get; set; }
        public decimal Actualpayments { get; set; }
        public int PayStatus { get; set; }
        public string CreateUserId { get; set; }
        public string Usrnbr { get; set; }
        public string PayUserId { get; set; }
        public string PayUserName { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public int IsExcess { get; set; }
        public string Mobile { get; set; }
        public int OrderFrom { get; set; }
        public int UserOrderStatus { get; set; }
    }
    
}
