//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.OrderPayModel
{
    public partial class F_Investment_Order_Push
    {
        public string Id { get; set; }
        public string OrderNo { get; set; }
        public string ProjectCode { get; set; }
        public string RunningNO { get; set; }
        public string Usrnbr { get; set; }
        public string Accseq { get; set; }
        public decimal PayAmount { get; set; }
        public int PayType { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string AreaCode { get; set; }
        public string Year { get; set; }
        public int YearIndex { get; set; }
        public int SendStatu { get; set; }
    }
    
}
