//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace My.DataAccess.OrderPayModel
{
    public partial class F_Order_CmdRequest
    {
        public string RequestNum { get; set; }
        public string ProjectCode { get; set; }
        public string OrderNo { get; set; }
        public string OrderDetailNo { get; set; }
        public int OrderType { get; set; }
        public int SendStatus { get; set; }
        public string SendResult { get; set; }
        public int RequestExcStatus { get; set; }
        public string RequestExcResult { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public int RequestType { get; set; }
        public string RequestExcXml { get; set; }
        public string RequestExcData { get; set; }
        public string RequestExcToken { get; set; }
        public string TransferTime { get; set; }
        public string RunningNo { get; set; }
        public string SerialNumber { get; set; }
    }
    
}
